stages:
    - build
    #- test
    - npm-publish
  
variables:
  VERSION: $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')

build_app:
  stage: build
  before_script:
    - npm install
  script:
    - cd projects/material-calendar/ && npm install
    - ng build material-calendar --prod
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  tags:
    - node

  #test:karma:chrome:
  #  stage: test
  #  allow_failure: false
  #  script:
  #    - npm install
  #    - ng test --watch=false --browsers='HeadlessChrome' --code-coverage --progress=false
  #  coverage: '/Statements\s+:\s(\d+.?\d+)%/'
  #  artifacts:
  #    paths:
  #      - coverage
  #    expire_in: 30 days
  #  tags:
  #    - ng-test
  #
  #test:protractor:chrome:
  #  stage: test
  #  allow_failure: true
  #  script:
  #    - npm install
  #    - ng e2e
  #    - mv screenshots/ public/
  #  artifacts:
  #    paths:
  #      - public
  #    expire_in: 30 days
  #  tags:
  #    - ng-test
  
npm-publish:
  stage: npm-publish
  script:
    - touch .npmrc
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - cd dist/material-calendar
    - npm publish
    - rm .npmrc
  tags:
    - node
  