name: Publish Release

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-node@v1
        with:
          node-versio: '14.x'
      - name: Set up awesome-ci
        run: |
          wget https://github.com/eksrvb/awesome-ci/releases/latest/download/awesome-ci
          chmod +x awesome-ci
      - name: install npm packages
        run: npm install
      - name: package Applikation
        run: npm run build
      - name: set publish config
        shell: bash
        run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release and Publish
        run: ./awesome-ci createRelease -publishNpm dist/material-calendar/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
